### ISSUE TITLE
Pease Transfer Ownership for Notes

### ISSUE THREAD

**Issue by nuttyartist** [dplanella/arduino-odb2sim#1]
Dear David,

I've been trying to contact you in many ways. I'm the founder of the note-taking app Notes https://github.com/nuttyartist/notes, where you helped package a snap version. But now, due to the fact that you're no longer active on the project and you're the owner of the account that uploaded our software, we can't update our app on the Ubuntu store, which is very unfortunate. Please, transfer the ownership to us.

Best,

Ruby

**Comment by dplanella** [comment]
Thanks Ruby. Closing issue as per the reply on https://github.com/nuttyartist/notes/issues/251

**Comment by nuttyartist** [comment]
Thank you! :)
